import type { Campaign, Product, ProductDraft } from './types';

export const demoProducts: Product[] = [
  {
    id: 1,
    name: 'Kit Organizador de Gaveta',
    sku: 'ORG-001',
    category: 'Casa & Organização',
    stock: 42,
    minStock: 15,
    weeklyOrders: 31,
    weeklyDelivered: 24,
    incoming: 30,
    costCents: 1280,
    saleCents: 2990,
    weeklyExpensesCents: 3400,
    weeklyAdSpendCents: 8500,
    weeklyAdRevenueCents: 47840,
  },
  {
    id: 2,
    name: 'Luminária LED de Mesa',
    sku: 'LED-014',
    category: 'Eletrônicos',
    stock: 9,
    minStock: 12,
    weeklyOrders: 18,
    weeklyDelivered: 15,
    incoming: 25,
    costCents: 2190,
    saleCents: 4990,
    weeklyExpensesCents: 2800,
    weeklyAdSpendCents: 6200,
    weeklyAdRevenueCents: 29940,
  },
  {
    id: 3,
    name: 'Garrafa Térmica 500 ml',
    sku: 'GAR-022',
    category: 'Cozinha',
    stock: 67,
    minStock: 20,
    weeklyOrders: 27,
    weeklyDelivered: 27,
    incoming: 0,
    costCents: 1850,
    saleCents: 4290,
    weeklyExpensesCents: 2600,
    weeklyAdSpendCents: 4800,
    weeklyAdRevenueCents: 21450,
  },
  {
    id: 4,
    name: 'Suporte Articulado para Celular',
    sku: 'SUP-008',
    category: 'Acessórios',
    stock: 4,
    minStock: 10,
    weeklyOrders: 13,
    weeklyDelivered: 8,
    incoming: 40,
    costCents: 940,
    saleCents: 2490,
    weeklyExpensesCents: 1900,
    weeklyAdSpendCents: 3600,
    weeklyAdRevenueCents: 12450,
  },
  {
    id: 5,
    name: 'Cabo USB-C Reforçado 2 m',
    sku: 'CAB-031',
    category: 'Acessórios',
    stock: 6,
    minStock: 18,
    weeklyOrders: 22,
    weeklyDelivered: 16,
    incoming: 60,
    costCents: 710,
    saleCents: 1890,
    weeklyExpensesCents: 1300,
    weeklyAdSpendCents: 2900,
    weeklyAdRevenueCents: 13230,
  },
];

export const emptyProductDraft: ProductDraft = {
  name: '',
  sku: '',
  category: 'Casa & Organização',
  stock: 0,
  minStock: 5,
  weeklyOrders: 0,
  weeklyDelivered: 0,
  incoming: 0,
  costCents: 0,
  saleCents: 0,
  weeklyExpensesCents: 0,
  weeklyAdSpendCents: 0,
  weeklyAdRevenueCents: 0,
};

export const campaigns: Campaign[] = [
  {
    id: 1,
    name: 'Organização que transforma',
    platform: 'Meta',
    budgetCents: 12000,
    spentCents: 8500,
    revenueCents: 47840,
    clicks: 612,
    conversions: 24,
    theme: 'forest',
    status: 'Ativa',
    isDemo: true,
  },
  {
    id: 2,
    name: 'Ilumine seu espaço',
    platform: 'Google',
    budgetCents: 9000,
    spentCents: 6200,
    revenueCents: 29940,
    clicks: 384,
    conversions: 15,
    theme: 'gold',
    status: 'Ativa',
    isDemo: true,
  },
  {
    id: 3,
    name: 'Acessórios essenciais',
    platform: 'Meta',
    budgetCents: 7500,
    spentCents: 3600,
    revenueCents: 12450,
    clicks: 291,
    conversions: 8,
    theme: 'blue',
    status: 'Ativa',
    isDemo: true,
  },
];

export const supplierBySku: Record<string, string> = {
  'LED-014': 'Lumi Importadora',
  'SUP-008': 'TechParts Brasil',
  'CAB-031': 'Connect Atacado',
};
